### ISSUE TITLE
Chybne tagy

### ISSUE THREAD

**Issue by gitpajo** [MichalDM/hello-world#5]
Chybne tagy muzes smazat - tlacitko delete

**Comment by gitpajo** [comment]
@MichalDM po editaci se vytvori novy, tak musis ten puvodni smazat

**Comment by myjavarama4** [comment]
go to hell

**Comment by gitpajo** [comment]
Kometare jen slusne

**Comment by myjavarama4** [comment]
Ty mluvíš sprostě

**Comment by gitpajo** [comment]
On github only decently
